# Generated by Django 5.0.4 on 2024-05-30 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man_fr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('auteur', models.CharField(max_length=200)),
                ('bug', models.TextField()),
                ('copyright', models.TextField()),
                ('also', models.TextField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='man_fr.topic')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
