# Generated by Django 5.0.6 on 2024-05-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man_fr', '0002_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='synopsis',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
